### ISSUE TITLE
Sequence diagrams: Download CAFF

### ISSUE THREAD

**Issue by nemkrisz11** [nemkrisz11/Computer-Security-Homework-2021-SHAjt#20]

**Comment by nemkrisz11** [comment]
@hbalint12 
Thanks! Some notes:

- .drawio file should always be downloaded, so others can edit the diagram later
- Arrow pointing from the actor to the first function call -> ???
- Username in function call should be replaced by something like "session" -> meaning that the auth component will check the validity of the session cookie of the user (which proves that they are logged in). This check would not work by username, it is spoofable this way, if you know the username of another user, who is currently logged in. It is easier to know someone's username, than knowing their server-generated session cookie, which gets invalidated on logout / timeout.
- CAFF db is duplicated, one of them was probably intended to be the log data handler.

**Comment by hbalint12** [comment]
https://github.com/nemkrisz11/Computer-Security-Homework-2021-SHAjt/commit/ac64734281aaf724054052d8b717b6072ca7f237

**Comment by hbalint12** [comment]
The png was updated and I commited the drawio file as well.
